//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBaybars.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BarkodcuboEntities : DbContext
    {
        public BarkodcuboEntities()
            : base("name=BarkodcuboEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AylikSayim> AylikSayim { get; set; }
        public virtual DbSet<Bay_SatisTarihi> Bay_SatisTarihi { get; set; }
        public virtual DbSet<SonSatislar> SonSatislar { get; set; }
        public virtual DbSet<BUGUN_SATILANLARIN_ADETI> BUGUN_SATILANLARIN_ADETI { get; set; }
        public virtual DbSet<UrunStokSonu> UrunStokSonu { get; set; }
    
        public virtual ObjectResult<Proc_UrunBilgisi_Result> Proc_UrunBilgisi(string barkod)
        {
            var barkodParameter = barkod != null ?
                new ObjectParameter("Barkod", barkod) :
                new ObjectParameter("Barkod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_UrunBilgisi_Result>("Proc_UrunBilgisi", barkodParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_UrunSatisAdeti(string barkod)
        {
            var barkodParameter = barkod != null ?
                new ObjectParameter("Barkod", barkod) :
                new ObjectParameter("Barkod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_UrunSatisAdeti", barkodParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_UrunStokBilgisi(string barkod)
        {
            var barkodParameter = barkod != null ?
                new ObjectParameter("Barkod", barkod) :
                new ObjectParameter("Barkod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_UrunStokBilgisi", barkodParameter);
        }
    
        public virtual ObjectResult<Proc_SatilanUrunuBarkodlaSatisToplaminiOgren_Result> Proc_SatilanUrunuBarkodlaSatisToplaminiOgren(string barkod)
        {
            var barkodParameter = barkod != null ?
                new ObjectParameter("Barkod", barkod) :
                new ObjectParameter("Barkod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_SatilanUrunuBarkodlaSatisToplaminiOgren_Result>("Proc_SatilanUrunuBarkodlaSatisToplaminiOgren", barkodParameter);
        }
    
        public virtual ObjectResult<ProcEncokSatilanUrunler_Result> ProcEncokSatilanUrunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcEncokSatilanUrunler_Result>("ProcEncokSatilanUrunler");
        }
    }
}
