//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBaybars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunStokSonu
    {
        public int Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<System.DateTime> UrunBittigiTarih { get; set; }
        public Nullable<int> ToplamSatilan { get; set; }
        public string Barkod { get; set; }
    }
}
